spring:
  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:

    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
server:
  port: 8887

#swagger:
#  enabled: true
#  title: 桥安科技
#  version: 1.0.0
#  description: web page
#  base-package: 基础路径(*重要*)
#  #作者
#  contact:
#    name: Az
#    email: azt0903@163.com
